# MIT License
#
# Copyright (c) 2025 Quandela
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""
Pure descriptive components that describe WHAT we want, not HOW to implement it.
Components are platform-agnostic and focus on intent rather than implementation.
"""

import math
import random
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

import torch


class ParameterRole(Enum):
    """Role definition for circuit parameters."""

    FIXED = "fixed"  # Fixed value, not a parameter
    INPUT = "input"  # Input parameter (fed from data)
    TRAINABLE = "trainable"  # Trainable parameter (nn.Parameter)
    MEMRISTOR = "memristor"  # Memristor parameters to be updated with respect to a rule


@dataclass
class Rotation:
    """Rotation gate description. The actual parameter name will be generated by the backend based on role.

    Parameters
    ----------
    target : int
        Target mode of the rotation.
    role : ParameterRole
        Parameter role of the rotation.
    value : float
        Fixed rotation value when ``role`` is ``ParameterRole.FIXED``.
    axis : str
        Rotation axis.
    custom_name : str | None
        Optional custom parameter name.
    """

    target: int
    role: ParameterRole = ParameterRole.FIXED
    value: float = 0.0  # Used when role=FIXED
    axis: str = "z"

    # Optional: let user specify custom name if they want
    custom_name: str | None = None

    def get_params(self) -> dict[str, Any]:
        """Return declared parameter placeholders for the rotation.

        Non-fixed rotations expose either their custom name or the automatically
        generated identifier so that downstream tooling can bind data or trainable
        tensors to the gate.

        Returns
        -------
        dict[str, Any]
            Mapping from parameter name to placeholder value.
        """
        if self.custom_name and self.role != ParameterRole.FIXED:
            return {
                self.custom_name: (
                    self.value if self.role == ParameterRole.FIXED else None
                )
            }
        return {}


@dataclass
class BeamSplitter:
    """Beam splitter description.

    Parameters
    ----------
    targets : tuple
        Pair of target modes.
    theta_role : ParameterRole
        Role of the mixing-angle parameter.
    theta_value : float
        Fixed value of the mixing angle when ``theta_role`` is fixed.
    phi_role : ParameterRole
        Role of the relative-phase parameter.
    phi_value : float
        Fixed value of the relative phase when ``phi_role`` is fixed.
    theta_name : str | None
        Optional symbolic name for the mixing-angle parameter.
    phi_name : str | None
        Optional symbolic name for the relative-phase parameter.
    """

    targets: tuple
    theta_role: ParameterRole = ParameterRole.FIXED
    theta_value: float = 0.7854  # pi/4 default
    phi_role: ParameterRole = ParameterRole.FIXED
    phi_value: float = 0.0

    # Optional custom names
    theta_name: str | None = None
    phi_name: str | None = None

    def get_params(self) -> dict[str, Any]:
        """Describe which phase shifter angles should be exposed as parameters.

        Returns
        -------
        dict[str, Any]
            Parameter placeholders keyed by their symbolic names.
        """
        params = dict[str, Any]()
        if self.theta_name and self.theta_role != ParameterRole.FIXED:
            params[self.theta_name] = None
        if self.phi_name and self.phi_role != ParameterRole.FIXED:
            params[self.phi_name] = None
        return params


@dataclass
class EntanglingBlock:
    """Entangling block description.

    Parameters
    ----------
    targets : str | list[int]
        Target modes or ``"all"`` for every mode.
    pattern : str
        Connectivity pattern for the entangling block.
    depth : int
        Number of repeated entangling passes.
    trainable : bool
        Whether the block should expose trainable parameters.
    name_prefix : str | None
        Optional prefix used when generating parameter names.
    """

    targets: str | list[int] = "all"
    pattern: str = "nearest_neighbor"
    depth: int = 1
    trainable: bool = True
    name_prefix: str | None = None

    def get_params(self) -> dict[str, Any]:
        """Entangling blocks themselves carry no direct parameters.

        Returns
        -------
        dict[str, Any]
            Always empty because entangling blocks are metadata-only.
        """
        return {}


@dataclass
class GenericInterferometer:
    """Generic interferometer block spanning multiple modes.

    Parameters
    ----------
    start_mode : int
        First mode covered by the interferometer.
    span : int
        Number of modes covered by the interferometer.
    trainable : bool
        Whether the interferometer exposes trainable parameters.
    name_prefix : str | None
        Optional prefix used when generating parameter names.
    model : str
        Interferometer model, either ``"mzi"`` or ``"bell"``.
    trainable_inner : bool | None
        Whether inner phase shifters are trainable.
    trainable_outer : bool | None
        Whether outer phase shifters are trainable.
    seed : int | None
        Optional seed controlling the random phases drawn for non-trainable
        inner/outer phase shifters. When omitted, a seed is drawn from
        PyTorch's global random generator, so ``torch.manual_seed`` controls
        reproducibility.
    fixed_inner_values : list[float]
        Fixed (non-trainable) values for the inner phase shifters, drawn
        randomly unless explicitly provided. When provided, must contain
        exactly ``span * (span - 1) // 2`` entries.
    fixed_outer_values : list[float]
        Fixed (non-trainable) values for the outer phase shifters, drawn
        randomly unless explicitly provided. When provided, must contain
        exactly ``span * (span - 1) // 2`` entries.

    Raises
    ------
    TypeError
        If ``model`` is not a string.
    ValueError
        If ``model`` is not ``"mzi"`` or ``"bell"``, or if a provided
        ``fixed_inner_values``/``fixed_outer_values`` list does not contain
        exactly one entry per phase shifter.
    """

    start_mode: int
    span: int
    trainable: bool = True
    name_prefix: str | None = None
    model: str = "mzi"
    trainable_inner: bool | None = None
    trainable_outer: bool | None = None
    seed: int | None = None
    fixed_inner_values: list[float] = field(default_factory=list)
    fixed_outer_values: list[float] = field(default_factory=list)

    def __post_init__(self):
        """Validate and normalize the interferometer configuration."""
        if not isinstance(self.model, str):
            raise TypeError("GenericInterferometer model must be provided as a string")
        normalized = (self.model or "mzi").lower()
        if normalized not in {"mzi", "bell"}:
            raise ValueError(
                "GenericInterferometer model must be either 'mzi' or 'bell'"
            )
        self.model = normalized
        if self.trainable_inner is None:
            self.trainable_inner = self.trainable
        if self.trainable_outer is None:
            self.trainable_outer = self.trainable
        if not self.trainable:
            self.trainable_inner = False
            self.trainable_outer = False
        # Normalise the aggregate flag so downstream logic can rely on it
        self.trainable = bool(self.trainable_inner or self.trainable_outer)

        # Non-trainable phase shifters must still be initialised to random
        # phases (not a constant 0.0), otherwise a "fixed" interferometer
        # degenerates into a deterministic swap/identity instead of the
        # random fixed unitary that untrained entangling layers are meant to
        # provide (e.g. for reservoir-computing style architectures).
        count = self.span * (self.span - 1) // 2 if self.span > 1 else 0
        # A partially filled list would silently fall back to 0.0 phases for
        # the missing indices downstream, so explicit values must cover every
        # phase shifter.
        for label, values in (
            ("fixed_inner_values", self.fixed_inner_values),
            ("fixed_outer_values", self.fixed_outer_values),
        ):
            if values and len(values) != count:
                raise ValueError(
                    f"GenericInterferometer {label} must contain exactly "
                    f"{count} entries for span {self.span}, got {len(values)}"
                )
        if count > 0:
            if self.seed is None and (
                not self.trainable_inner or not self.trainable_outer
            ):
                self.seed = int(torch.randint(0, 2**31 - 1, ()).item())
            rng = random.Random(self.seed)
            if not self.trainable_inner and not self.fixed_inner_values:
                self.fixed_inner_values = [
                    rng.uniform(0, 2 * math.pi) for _ in range(count)
                ]
            if not self.trainable_outer and not self.fixed_outer_values:
                self.fixed_outer_values = [
                    rng.uniform(0, 2 * math.pi) for _ in range(count)
                ]

    def get_params(self) -> dict[str, Any]:
        """Return placeholder names for every internal interferometer parameter.

        Returns
        -------
        dict[str, Any]
            Mapping of generated parameter names to ``None`` placeholders.
        """
        if self.span < 2 or not self.trainable:
            return {}

        prefix = self.name_prefix or "gi"
        count = self.span * (self.span - 1) // 2
        params: dict[str, Any] = {}
        for idx in range(count):
            if self.trainable_inner:
                params[f"{prefix}_li{idx}"] = None
            if self.trainable_outer:
                params[f"{prefix}_lo{idx}"] = None
        return params


# For backward compatibility, keep old interface but map to new
class Component:
    """Backward-compatible component base class."""

    pass
